server.port=8088
#spring.datasource.url=jdbc:postgresql://localhost:5432/rigel_electronic_cloud_test
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.datasource.url=jdbc:hsqldb:file:D:/Java/todoapptest/data/eimddb;shutdown=true
spring.datasource.url=jdbc:hsqldb:file:./data/eimddb;shutdown=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.default_schema=PUBLIC
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


##spring.datasource.url=jdbc:hsqldb:mem:testdb
#spring.datasource.url=jdbc:hsqldb:file:./data/eimddb;shutdown=true
#spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
#spring.datasource.username=SA
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
##spring.hsqldb.console.enabled=true
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.default_schema=PUBLIC
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
##spring.jpa.properties.hibernate.globally_quoted_identifiers=true

